{"uuid": "b463b61f-3fc2-4351-a754-33cc83e2895e", "children": ["ae46c746-b6f7-45d9-a952-312ab6ecb801", "4070bcd1-dbfc-4bd4-9e12-56375b4e292e", "d0b4aae5-a0fa-411f-89d3-e641ca90b02b", "e700edd3-56f0-4dc4-aa93-ca83d4288c49", "a878895a-ede3-447e-b066-10ef2d7472fb"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.casaautoiasi.ro', port=443): Max retries exceeded with url: /cariere/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7feefa716200>: Failed to resolve 'www.casaautoiasi.ro' ([Errno -2] Name or service not known)\"))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_casaautoiasi.py\", line 14, in get_job_details\n    scraper_data = casaautoiasiScraper().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/casaautoiasi.py\", line 43, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/casaautoiasi.py\", line 26, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1713417085505, "stop": 1713417085690}], "start": 1713417085505, "stop": 1713417086172}