{"uuid": "accaa84d-21b7-4c43-a8f2-aa0e49b2e3a7", "children": ["bcd3abcd-6a1d-4c38-95ef-d218ae9664ad", "0fd577a4-0720-4b81-826c-a9f1b7f28559", "bb795cb7-dd81-4ce4-a413-d719aa740c41", "bd404886-31fe-4371-a1df-6dabefad70b8"], "befores": [{"name": "setup_tests", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPConnectionPool(host='iasi-delivery.rocariere-horeca', port=80): Max retries exceeded with url: / (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f567715dea0>: Failed to resolve 'iasi-delivery.rocariere-horeca' ([Errno -2] Name or service not known)\"))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/test_api.py\", line 47, in setup_tests\n    setup_tests_instance.get_jobs_careers(scraper_class)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/test_api.py\", line 32, in get_jobs_careers\n    self.scraper_data = scraper_class().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/iasidelivery.py\", line 54, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/iasidelivery.py\", line 26, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 725, in send\n    history = [resp for resp in gen]\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 725, in <listcomp>\n    history = [resp for resp in gen]\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 266, in resolve_redirects\n    resp = self.send(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1705295403756, "stop": 1705295404708}], "start": 1705295403756, "stop": 1705295405280}