{"uuid": "73abfd95-6559-47b4-89be-5bbb526bed17", "children": ["6a6907d2-e833-48b1-8a73-90af18af9568", "015fa428-9440-40b6-9cf1-8d5104a89bdb", "16314a1f-6eaa-410e-94c7-db908673efd1", "4b5d4e9a-f9a8-40bf-8086-f55239a4c9f1", "9837013d-65c9-4df5-b334-2e492e3f35e2"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.casaautoiasi.ro', port=443): Max retries exceeded with url: /cariere/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f9292ec11e0>: Failed to resolve 'www.casaautoiasi.ro' ([Errno -2] Name or service not known)\"))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_casaautoiasi.py\", line 14, in get_job_details\n    scraper_data = casaautoiasiScraper().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/casaautoiasi.py\", line 43, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/casaautoiasi.py\", line 26, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1718428310868, "stop": 1718428311174}], "start": 1718428310868, "stop": 1718428311686}