{"uuid": "9f7d63f5-3ee6-46f0-bf20-5381641c7558", "children": ["82ba14d2-29a4-4bfc-96b6-4dfe5e3d9e70", "6e490f73-a421-4f64-9fe5-e8027501c566", "725dbda4-a1f8-4165-b094-96b708bd4020", "bd63c36b-fd6f-46a6-a2b2-443115397bf6", "26eb09b3-2667-4287-ac7a-21cdb31a7661"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.casaautoiasi.ro', port=443): Max retries exceeded with url: /cariere/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7fcbafc43220>: Failed to resolve 'www.casaautoiasi.ro' ([Errno -2] Name or service not known)\"))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_casaautoiasi.py\", line 14, in get_job_details\n    scraper_data = casaautoiasiScraper().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/casaautoiasi.py\", line 43, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/casaautoiasi.py\", line 26, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/requests/adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1711689021007, "stop": 1711689021191}], "start": 1711689021007, "stop": 1711689021722}